<?php
declare(strict_types=1);

namespace Tylio\Services;

/**
 * Single source of truth for the available block types.
 * Each type declares: label, icon, description, category, default data,
 * and a field schema (for the admin form-editor).
 *
 * The "schema" is an array of fields. Each field has:
 *   - key   : field name inside `data`
 *   - label : UI label
 *   - type  : text | textarea | markdown | url | email | image | color | number |
 *             toggle | select | repeat | icon | range
 *   - help? : helper text
 *   - options? : array of {value, label} for selects
 *   - of?   : for type=repeat, item schema
 *   - max?  : repeat cap / max number / max length
 *   - default? : initial value
 *   - placeholder?
 *
 * **i18n.** This class is intentionally a pure data structure with no
 * user-visible strings in any one language: every label, help, description,
 * category, placeholder, user-visible default, and select-option label is a
 * translation key under the `blocks.*` namespace, resolved at the controller
 * boundary against `app/Locales/<lang>.php`. To localize the admin sheet,
 * add/override entries in the locale files — do NOT edit this file.
 *
 * Naming convention for keys:
 *   - `blocks.{type}.label` / `blocks.{type}.description`
 *   - `blocks.{type}.category` (or `blocks.categories.{name}`)
 *   - `blocks.{type}.fields.{key}.label|help|placeholder|default`
 *   - `blocks.{type}.fields.{key}.of.{subkey}.label|help|placeholder`
 *   - `blocks.{type}.fields.{key}.options.{value}` (select option label)
 */
final class BlockRegistry
{
    /**
     * Memoized output of `definitions()` for the lifetime of this
     * instance (one per request, bound as singleton in the DI
     * container). The data is pure and ~600 lines — recomputing it on
     * every `get()`/`all()` was a free no-op tax.
     *
     * @var array<string,array<string,mixed>>|null
     */
    private ?array $cache = null;

    public function all(): array { return $this->definitions(); }

    public function get(string $type): ?array
    {
        return $this->definitions()[$type] ?? null;
    }

    public function defaultData(string $type): array
    {
        $def = $this->get($type);
        if (!$def) return [];
        return self::extractDefaults($def['fields'] ?? []);
    }

    /**
     * Recursively walk a registry subtree (the full schema, a single block
     * definition, or a `defaultData` result) and resolve every string value
     * that looks like a `blocks.*` translation key through the given `I18n`
     * service. Other values pass through untouched.
     *
     * This is the seam used by `TypesController` (for the schema sent to
     * the SPA) and `BlocksController::create` (for the server-side default
     * data persisted when the SPA doesn't supply one).
     *
     * @param array<int|string, mixed> $node
     * @return array<int|string, mixed>
     */
    public static function resolveStrings(array $node, I18n $i18n): array
    {
        foreach ($node as $key => $value) {
            if (is_array($value)) {
                $node[$key] = self::resolveStrings($value, $i18n);
            } elseif (is_string($value) && str_starts_with($value, 'blocks.')) {
                $node[$key] = $i18n->t($value);
            }
        }
        return $node;
    }

    private static function extractDefaults(array $fields): array
    {
        $out = [];
        foreach ($fields as $f) {
            if (!isset($f['key'])) continue;
            if (($f['type'] ?? '') === 'repeat') {
                $out[$f['key']] = $f['default'] ?? [];
            } else {
                $out[$f['key']] = $f['default'] ?? '';
            }
        }
        return $out;
    }

    private function definitions(): array
    {
        if ($this->cache !== null) return $this->cache;
        return $this->cache = [
            'hero' => [
                'id' => 'hero',
                'label' => 'blocks.hero.label',
                'icon' => 'lucide:contact',
                'category' => 'blocks.categories.identity',
                'description' => 'blocks.hero.description',
                'span' => 'full', // how it behaves in the desktop mosaic
                'fields' => [
                    ['key' => 'avatar', 'label' => 'blocks.hero.fields.avatar.label', 'type' => 'avatar', 'help' => 'blocks.hero.fields.avatar.help'],
                    ['key' => 'title', 'label' => 'blocks.hero.fields.title.label', 'type' => 'text', 'default' => 'blocks.hero.fields.title.default', 'placeholder' => 'blocks.hero.fields.title.placeholder', 'help' => 'blocks.hero.fields.title.help'],
                    ['key' => 'title_image', 'label' => 'blocks.hero.fields.title_image.label', 'type' => 'image', 'help' => 'blocks.hero.fields.title_image.help'],
                    ['key' => 'subtitle', 'label' => 'blocks.hero.fields.subtitle.label', 'type' => 'markdown', 'default' => '', 'placeholder' => 'blocks.hero.fields.subtitle.placeholder', 'help' => 'blocks.hero.fields.subtitle.help'],
                ],
            ],

            'links' => [
                'id' => 'links',
                'label' => 'blocks.links.label',
                'icon' => 'lucide:link',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.links.description',
                'span' => 'half',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.links.fields.title.label', 'type' => 'text', 'default' => 'blocks.links.fields.title.default'],
                    ['key' => 'items', 'label' => 'blocks.links.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'label', 'label' => 'blocks.links.fields.items.of.label.label', 'type' => 'text'],
                            ['key' => 'url', 'label' => 'blocks.links.fields.items.of.url.label', 'type' => 'url'],
                            ['key' => 'icon_mode', 'label' => 'blocks.links.fields.items.of.icon_mode.label', 'type' => 'radio_cards', 'default' => 'favicon',
                                'options' => [
                                    ['value' => 'favicon', 'label' => 'blocks.links.fields.items.of.icon_mode.options.favicon.label', 'description' => 'blocks.links.fields.items.of.icon_mode.options.favicon.description'],
                                    ['value' => 'custom', 'label' => 'blocks.links.fields.items.of.icon_mode.options.custom.label', 'description' => 'blocks.links.fields.items.of.icon_mode.options.custom.description'],
                                ],
                            ],
                            ['key' => 'icon', 'label' => 'blocks.links.fields.items.of.icon.label', 'type' => 'icon', 'help' => 'blocks.links.fields.items.of.icon.help', 'show_when' => ['key' => 'icon_mode', 'equals' => 'custom']],
                            ['key' => '_badge_group', 'label' => 'blocks.links.fields.items.of.badge.label', 'type' => 'inline_group',
                                'of' => [
                                    ['key' => 'badge', 'label' => 'blocks.links.fields.items.of.badge.label', 'type' => 'text', 'placeholder' => 'blocks.links.fields.items.of.badge.placeholder'],
                                    ['key' => 'badge_copyable', 'label' => 'blocks.links.fields.items.of.badge_copyable.label', 'type' => 'toggle', 'default' => false],
                                ],
                            ],
                            ['key' => 'description', 'label' => 'blocks.links.fields.items.of.description.label', 'type' => 'text'],
                        ],
                    ],
                ],
            ],

            'apps' => [
                'id' => 'apps',
                'label' => 'blocks.apps.label',
                'icon' => 'lucide:layout-grid',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.apps.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.apps.fields.title.label', 'type' => 'text', 'default' => 'blocks.apps.fields.title.default'],
                    ['key' => 'subtitle', 'label' => 'blocks.apps.fields.subtitle.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'items', 'label' => 'blocks.apps.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'name', 'label' => 'blocks.apps.fields.items.of.name.label', 'type' => 'text'],
                            ['key' => 'tagline', 'label' => 'blocks.apps.fields.items.of.tagline.label', 'type' => 'text'],
                            ['key' => 'description', 'label' => 'blocks.apps.fields.items.of.description.label', 'type' => 'textarea'],
                            ['key' => 'icon_image', 'label' => 'blocks.apps.fields.items.of.icon_image.label', 'type' => 'image'],
                            ['key' => 'cover_image', 'label' => 'blocks.apps.fields.items.of.cover_image.label', 'type' => 'image'],
                            ['key' => 'accent', 'label' => 'blocks.apps.fields.items.of.accent.label', 'type' => 'color', 'default' => ''],
                            ['key' => 'url', 'label' => 'blocks.apps.fields.items.of.url.label', 'type' => 'url'],
                            ['key' => 'app_store', 'label' => 'blocks.apps.fields.items.of.app_store.label', 'type' => 'url'],
                            ['key' => 'play_store', 'label' => 'blocks.apps.fields.items.of.play_store.label', 'type' => 'url'],
                            ['key' => 'tag', 'label' => 'blocks.apps.fields.items.of.tag.label', 'type' => 'text', 'placeholder' => 'blocks.apps.fields.items.of.tag.placeholder', 'help' => 'blocks.apps.fields.items.of.tag.help'],
                        ],
                    ],
                ],
            ],

            'bio' => [
                'id' => 'bio',
                'label' => 'blocks.bio.label',
                'icon' => 'lucide:circle-user',
                'category' => 'blocks.categories.identity',
                'description' => 'blocks.bio.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.bio.fields.title.label', 'type' => 'text', 'default' => 'blocks.bio.fields.title.default'],
                    ['key' => 'body', 'label' => 'blocks.bio.fields.body.label', 'type' => 'markdown', 'default' => ''],
                ],
            ],

            'products' => [
                'id' => 'products',
                'label' => 'blocks.products.label',
                'icon' => 'lucide:shopping-bag',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.products.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.products.fields.title.label', 'type' => 'text', 'default' => 'blocks.products.fields.title.default'],
                    ['key' => 'subtitle', 'label' => 'blocks.products.fields.subtitle.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'cta_label', 'label' => 'blocks.products.fields.cta_label.label', 'type' => 'text', 'default' => 'blocks.products.fields.cta_label.default', 'help' => 'blocks.products.fields.cta_label.help'],
                    ['key' => 'items', 'label' => 'blocks.products.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'image', 'label' => 'blocks.products.fields.items.of.image.label', 'type' => 'image'],
                            ['key' => 'name', 'label' => 'blocks.products.fields.items.of.name.label', 'type' => 'text'],
                            ['key' => 'description', 'label' => 'blocks.products.fields.items.of.description.label', 'type' => 'textarea'],
                            ['key' => 'price', 'label' => 'blocks.products.fields.items.of.price.label', 'type' => 'text', 'help' => 'blocks.products.fields.items.of.price.help'],
                            ['key' => 'url', 'label' => 'blocks.products.fields.items.of.url.label', 'type' => 'url'],
                            ['key' => 'discount_code', 'label' => 'blocks.products.fields.items.of.discount_code.label', 'type' => 'text', 'help' => 'blocks.products.fields.items.of.discount_code.help'],
                            ['key' => 'discount_label', 'label' => 'blocks.products.fields.items.of.discount_label.label', 'type' => 'text', 'help' => 'blocks.products.fields.items.of.discount_label.help'],
                        ],
                    ],
                ],
            ],

            'quote' => [
                'id' => 'quote',
                'label' => 'blocks.quote.label',
                'icon' => 'lucide:quote',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.quote.description',
                'span' => 'half',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.quote.fields.title.label', 'type' => 'text', 'default' => '', 'help' => 'blocks.quote.fields.title.help'],
                    ['key' => 'text', 'label' => 'blocks.quote.fields.text.label', 'type' => 'textarea', 'default' => '', 'placeholder' => 'blocks.quote.fields.text.placeholder'],
                    ['key' => 'author', 'label' => 'blocks.quote.fields.author.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'role', 'label' => 'blocks.quote.fields.role.label', 'type' => 'text', 'default' => '', 'help' => 'blocks.quote.fields.role.help'],
                    ['key' => 'avatar', 'label' => 'blocks.quote.fields.avatar.label', 'type' => 'image'],
                    ['key' => 'style', 'label' => 'blocks.quote.fields.style.label', 'type' => 'select', 'default' => 'card',
                        'options' => [
                            ['value' => 'card', 'label' => 'blocks.quote.fields.style.options.card'],
                            ['value' => 'minimal', 'label' => 'blocks.quote.fields.style.options.minimal'],
                            ['value' => 'highlight', 'label' => 'blocks.quote.fields.style.options.highlight'],
                        ],
                    ],
                    ['key' => 'text_size', 'label' => 'blocks.quote.fields.text_size.label', 'type' => 'select', 'default' => 'md',
                        'options' => [
                            ['value' => 'sm', 'label' => 'blocks.quote.fields.text_size.options.sm'],
                            ['value' => 'md', 'label' => 'blocks.quote.fields.text_size.options.md'],
                            ['value' => 'lg', 'label' => 'blocks.quote.fields.text_size.options.lg'],
                        ],
                        'help' => 'blocks.quote.fields.text_size.help',
                    ],
                    ['key' => 'line_height', 'label' => 'blocks.quote.fields.line_height.label', 'type' => 'select', 'default' => 'normal',
                        'options' => [
                            ['value' => 'compact', 'label' => 'blocks.quote.fields.line_height.options.compact'],
                            ['value' => 'normal', 'label' => 'blocks.quote.fields.line_height.options.normal'],
                            ['value' => 'relaxed', 'label' => 'blocks.quote.fields.line_height.options.relaxed'],
                        ],
                        'help' => 'blocks.quote.fields.line_height.help',
                    ],
                ],
            ],

            'stats' => [
                'id' => 'stats',
                'label' => 'blocks.stats.label',
                'icon' => 'lucide:bar-chart-3',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.stats.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.stats.fields.title.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'items', 'label' => 'blocks.stats.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'value', 'label' => 'blocks.stats.fields.items.of.value.label', 'type' => 'text', 'help' => 'blocks.stats.fields.items.of.value.help'],
                            ['key' => 'label', 'label' => 'blocks.stats.fields.items.of.label.label', 'type' => 'text'],
                            ['key' => 'icon', 'label' => 'blocks.stats.fields.items.of.icon.label', 'type' => 'icon'],
                        ],
                    ],
                ],
            ],

            'skills' => [
                'id' => 'skills',
                'label' => 'blocks.skills.label',
                'icon' => 'lucide:sparkles',
                'category' => 'blocks.categories.identity',
                'description' => 'blocks.skills.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.skills.fields.title.label', 'type' => 'text', 'default' => 'blocks.skills.fields.title.default'],
                    ['key' => 'subtitle', 'label' => 'blocks.skills.fields.subtitle.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'items', 'label' => 'blocks.skills.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'name', 'label' => 'blocks.skills.fields.items.of.name.label', 'type' => 'text', 'placeholder' => 'blocks.skills.fields.items.of.name.placeholder'],
                            ['key' => 'level', 'label' => 'blocks.skills.fields.items.of.level.label', 'type' => 'text', 'placeholder' => 'blocks.skills.fields.items.of.level.placeholder', 'help' => 'blocks.skills.fields.items.of.level.help'],
                            ['key' => 'category', 'label' => 'blocks.skills.fields.items.of.category.label', 'type' => 'text', 'placeholder' => 'blocks.skills.fields.items.of.category.placeholder', 'help' => 'blocks.skills.fields.items.of.category.help', 'autocomplete_from' => 'siblings'],
                            ['key' => 'icon', 'label' => 'blocks.skills.fields.items.of.icon.label', 'type' => 'icon'],
                        ],
                    ],
                ],
            ],

            'cta' => [
                'id' => 'cta',
                'label' => 'blocks.cta.label',
                'icon' => 'lucide:mouse-pointer-click',
                'category' => 'blocks.categories.action',
                'description' => 'blocks.cta.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.cta.fields.title.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'subtitle', 'label' => 'blocks.cta.fields.subtitle.label', 'type' => 'textarea', 'default' => ''],
                    ['key' => 'button_label', 'label' => 'blocks.cta.fields.button_label.label', 'type' => 'text', 'default' => 'blocks.cta.fields.button_label.default'],
                    ['key' => 'button_url', 'label' => 'blocks.cta.fields.button_url.label', 'type' => 'url', 'default' => ''],
                    ['key' => 'icon', 'label' => 'blocks.cta.fields.icon.label', 'type' => 'icon'],
                    ['key' => 'style', 'label' => 'blocks.cta.fields.style.label', 'type' => 'select', 'default' => 'gradient',
                        'options' => [
                            ['value' => 'gradient', 'label' => 'blocks.cta.fields.style.options.gradient'],
                            ['value' => 'solid', 'label' => 'blocks.cta.fields.style.options.solid'],
                            ['value' => 'outline', 'label' => 'blocks.cta.fields.style.options.outline'],
                            ['value' => 'minimal', 'label' => 'blocks.cta.fields.style.options.minimal'],
                        ],
                    ],
                ],
            ],

            'faq' => [
                'id' => 'faq',
                'label' => 'blocks.faq.label',
                'icon' => 'lucide:circle-help',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.faq.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.faq.fields.title.label', 'type' => 'text', 'default' => 'blocks.faq.fields.title.default'],
                    ['key' => 'items', 'label' => 'blocks.faq.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'question', 'label' => 'blocks.faq.fields.items.of.question.label', 'type' => 'text'],
                            ['key' => 'answer', 'label' => 'blocks.faq.fields.items.of.answer.label', 'type' => 'markdown'],
                        ],
                    ],
                ],
            ],

            'timeline' => [
                'id' => 'timeline',
                'label' => 'blocks.timeline.label',
                'icon' => 'lucide:timer',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.timeline.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.timeline.fields.title.label', 'type' => 'text', 'default' => 'blocks.timeline.fields.title.default'],
                    ['key' => 'items', 'label' => 'blocks.timeline.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'date', 'label' => 'blocks.timeline.fields.items.of.date.label', 'type' => 'text', 'help' => 'blocks.timeline.fields.items.of.date.help'],
                            ['key' => 'title', 'label' => 'blocks.timeline.fields.items.of.title.label', 'type' => 'text'],
                            ['key' => 'description', 'label' => 'blocks.timeline.fields.items.of.description.label', 'type' => 'textarea'],
                            ['key' => 'icon', 'label' => 'blocks.timeline.fields.items.of.icon.label', 'type' => 'icon'],
                            ['key' => 'highlight', 'label' => 'blocks.timeline.fields.items.of.highlight.label', 'type' => 'toggle', 'default' => false, 'help' => 'blocks.timeline.fields.items.of.highlight.help'],
                        ],
                    ],
                ],
            ],

            'social' => [
                'id' => 'social',
                'label' => 'blocks.social.label',
                'icon' => 'lucide:share-2',
                'category' => 'blocks.categories.identity',
                'description' => 'blocks.social.description',
                'span' => 'half',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.social.fields.title.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'display', 'label' => 'blocks.social.fields.display.label', 'type' => 'select', 'default' => 'icon_platform',
                        'help' => 'blocks.social.fields.display.help',
                        'options' => [
                            ['value' => 'icon_only', 'label' => 'blocks.social.fields.display.options.icon_only'],
                            ['value' => 'icon_platform', 'label' => 'blocks.social.fields.display.options.icon_platform'],
                            ['value' => 'icon_account', 'label' => 'blocks.social.fields.display.options.icon_account'],
                            ['value' => 'icon_full', 'label' => 'blocks.social.fields.display.options.icon_full'],
                        ],
                    ],
                    ['key' => 'align', 'label' => 'blocks.social.fields.align.label', 'type' => 'select', 'default' => 'left',
                        'help' => 'blocks.social.fields.align.help',
                        'options' => [
                            ['value' => 'left', 'label' => 'blocks.social.fields.align.options.left'],
                            ['value' => 'center', 'label' => 'blocks.social.fields.align.options.center'],
                        ],
                    ],
                    ['key' => 'items', 'label' => 'blocks.social.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'platform', 'label' => 'blocks.social.fields.items.of.platform.label', 'type' => 'select', 'options' => [
                                // === Main social networks ===
                                ['value' => 'twitter', 'label' => 'X / Twitter'],
                                ['value' => 'instagram', 'label' => 'Instagram'],
                                ['value' => 'youtube', 'label' => 'YouTube'],
                                ['value' => 'tiktok', 'label' => 'TikTok'],
                                ['value' => 'threads', 'label' => 'Threads'],
                                ['value' => 'bluesky', 'label' => 'Bluesky'],
                                ['value' => 'mastodon', 'label' => 'Mastodon'],
                                ['value' => 'facebook', 'label' => 'Facebook'],
                                ['value' => 'linkedin', 'label' => 'LinkedIn'],
                                ['value' => 'pinterest', 'label' => 'Pinterest'],
                                ['value' => 'snapchat', 'label' => 'Snapchat'],
                                // === Dev / open source ===
                                ['value' => 'github', 'label' => 'GitHub'],
                                ['value' => 'gitlab', 'label' => 'GitLab'],
                                ['value' => 'codepen', 'label' => 'CodePen'],
                                ['value' => 'stackoverflow', 'label' => 'Stack Overflow'],
                                // === Design / portfolio ===
                                ['value' => 'dribbble', 'label' => 'Dribbble'],
                                ['value' => 'behance', 'label' => 'Behance'],
                                ['value' => 'figma', 'label' => 'Figma'],
                                // === 3D / Maker ===
                                ['value' => 'makerworld', 'label' => 'MakerWorld'],
                                ['value' => 'printables', 'label' => 'Printables'],
                                ['value' => 'thingiverse', 'label' => 'Thingiverse'],
                                ['value' => 'cults3d', 'label' => 'Cults3D'],
                                ['value' => 'thangs', 'label' => 'Thangs'],
                                ['value' => 'sketchfab', 'label' => 'Sketchfab'],
                                ['value' => 'cgtrader', 'label' => 'CGTrader'],
                                // === Video / streaming ===
                                ['value' => 'twitch', 'label' => 'Twitch'],
                                ['value' => 'vimeo', 'label' => 'Vimeo'],
                                // === Audio ===
                                ['value' => 'spotify', 'label' => 'Spotify'],
                                ['value' => 'soundcloud', 'label' => 'SoundCloud'],
                                ['value' => 'applemusic', 'label' => 'Apple Music'],
                                ['value' => 'bandcamp', 'label' => 'Bandcamp'],
                                // === Writing ===
                                ['value' => 'medium', 'label' => 'Medium'],
                                ['value' => 'substack', 'label' => 'Substack'],
                                ['value' => 'devto', 'label' => 'dev.to'],
                                ['value' => 'hashnode', 'label' => 'Hashnode'],
                                // === Community / chat ===
                                ['value' => 'discord', 'label' => 'Discord'],
                                ['value' => 'telegram', 'label' => 'Telegram'],
                                ['value' => 'whatsapp', 'label' => 'WhatsApp'],
                                ['value' => 'reddit', 'label' => 'Reddit'],
                                ['value' => 'matrix', 'label' => 'Matrix'],
                                // === Support / tip ===
                                ['value' => 'patreon', 'label' => 'Patreon'],
                                ['value' => 'kofi', 'label' => 'Ko-fi'],
                                ['value' => 'buymeacoffee', 'label' => 'Buy Me a Coffee'],
                                ['value' => 'liberapay', 'label' => 'Liberapay'],
                                // === Generic ===
                                ['value' => 'website', 'label' => 'blocks.social.fields.items.of.platform.options.website'],
                                ['value' => 'email', 'label' => 'blocks.social.fields.items.of.platform.options.email'],
                                ['value' => 'phone', 'label' => 'blocks.social.fields.items.of.platform.options.phone'],
                                ['value' => 'rss', 'label' => 'RSS'],
                                ['value' => 'other', 'label' => 'blocks.social.fields.items.of.platform.options.other'],
                            ]],
                            ['key' => 'url', 'label' => 'blocks.social.fields.items.of.url.label', 'type' => 'url'],
                            ['key' => 'label', 'label' => 'blocks.social.fields.items.of.label.label', 'type' => 'text', 'help' => 'blocks.social.fields.items.of.label.help'],
                        ],
                    ],
                ],
            ],

            'gallery' => [
                'id' => 'gallery',
                'label' => 'blocks.gallery.label',
                'icon' => 'lucide:images',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.gallery.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.gallery.fields.title.label', 'type' => 'text', 'default' => 'blocks.gallery.fields.title.default'],
                    ['key' => 'layout', 'label' => 'blocks.gallery.fields.layout.label', 'type' => 'select', 'default' => 'mosaic',
                        'options' => [
                            ['value' => 'mosaic', 'label' => 'blocks.gallery.fields.layout.options.mosaic'],
                            ['value' => 'grid', 'label' => 'blocks.gallery.fields.layout.options.grid'],
                            ['value' => 'carousel', 'label' => 'blocks.gallery.fields.layout.options.carousel'],
                        ],
                    ],
                    ['key' => 'items', 'label' => 'blocks.gallery.fields.items.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'image', 'label' => 'blocks.gallery.fields.items.of.image.label', 'type' => 'image'],
                            ['key' => 'alt', 'label' => 'blocks.gallery.fields.items.of.alt.label', 'type' => 'text'],
                            ['key' => 'caption', 'label' => 'blocks.gallery.fields.items.of.caption.label', 'type' => 'text'],
                            ['key' => 'link', 'label' => 'blocks.gallery.fields.items.of.link.label', 'type' => 'url'],
                        ],
                    ],
                ],
            ],

            'podcast' => [
                'id' => 'podcast',
                'label' => 'blocks.podcast.label',
                'icon' => 'lucide:podcast',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.podcast.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.podcast.fields.title.label', 'type' => 'text', 'default' => 'blocks.podcast.fields.title.default'],
                    ['key' => 'subtitle', 'label' => 'blocks.podcast.fields.subtitle.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'show_name', 'label' => 'blocks.podcast.fields.show_name.label', 'type' => 'text',
                        'default' => '',
                        'placeholder' => 'blocks.podcast.fields.show_name.placeholder',
                        'help' => 'blocks.podcast.fields.show_name.help',
                    ],
                    ['key' => 'apple_url', 'label' => 'blocks.podcast.fields.apple_url.label', 'type' => 'url',
                        'default' => '',
                        'placeholder' => 'https://podcasts.apple.com/it/podcast/…/idNNN',
                        'help' => 'blocks.podcast.fields.apple_url.help',
                    ],
                    ['key' => 'spotify_url', 'label' => 'blocks.podcast.fields.spotify_url.label', 'type' => 'url',
                        'default' => '',
                        'placeholder' => 'https://open.spotify.com/show/… oppure /episode/…',
                        'help' => 'blocks.podcast.fields.spotify_url.help',
                    ],
                    ['key' => 'site_url', 'label' => 'blocks.podcast.fields.site_url.label', 'type' => 'url',
                        'default' => '',
                        'placeholder' => 'https://miopodcast.it',
                        'help' => 'blocks.podcast.fields.site_url.help',
                    ],
                    ['key' => 'preferred_player', 'label' => 'blocks.podcast.fields.preferred_player.label', 'type' => 'select', 'default' => 'auto',
                        'options' => [
                            ['value' => 'auto', 'label' => 'blocks.podcast.fields.preferred_player.options.auto'],
                            ['value' => 'spotify', 'label' => 'Spotify'],
                            ['value' => 'apple', 'label' => 'Apple Podcasts'],
                            ['value' => 'none', 'label' => 'blocks.podcast.fields.preferred_player.options.none'],
                        ],
                        'help' => 'blocks.podcast.fields.preferred_player.help',
                    ],
                    ['key' => 'description', 'label' => 'blocks.podcast.fields.description.label', 'type' => 'textarea',
                        'default' => '',
                        'placeholder' => 'blocks.podcast.fields.description.placeholder',
                    ],
                ],
            ],

            'youtube' => [
                'id' => 'youtube',
                'label' => 'blocks.youtube.label',
                'icon' => 'simple-icons:youtube',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.youtube.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.youtube.fields.title.label', 'type' => 'text', 'default' => 'blocks.youtube.fields.title.default'],
                    ['key' => 'subtitle', 'label' => 'blocks.youtube.fields.subtitle.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'source_url', 'label' => 'blocks.youtube.fields.source_url.label', 'type' => 'url',
                        'placeholder' => 'https://www.youtube.com/channel/UCxxx oppure …/playlist?list=PLxxx',
                        'help' => 'blocks.youtube.fields.source_url.help',
                    ],
                    ['key' => 'mode', 'label' => 'blocks.youtube.fields.mode.label', 'type' => 'select', 'default' => 'latest',
                        'options' => [
                            ['value' => 'latest', 'label' => 'blocks.youtube.fields.mode.options.latest'],
                            ['value' => 'playlist', 'label' => 'blocks.youtube.fields.mode.options.playlist'],
                        ],
                        'help' => 'blocks.youtube.fields.mode.help',
                    ],
                    ['key' => 'aspect', 'label' => 'blocks.youtube.fields.aspect.label', 'type' => 'select', 'default' => '16:9',
                        'options' => [
                            ['value' => '16:9', 'label' => 'blocks.youtube.fields.aspect.options.16_9'],
                            ['value' => '9:16', 'label' => 'blocks.youtube.fields.aspect.options.9_16'],
                            ['value' => '4:3', 'label' => '4:3'],
                            ['value' => '1:1', 'label' => 'blocks.youtube.fields.aspect.options.1_1'],
                        ],
                    ],
                ],
            ],

            'embed' => [
                'id' => 'embed',
                'label' => 'blocks.embed.label',
                'icon' => 'lucide:app-window',
                'category' => 'blocks.categories.content',
                'description' => 'blocks.embed.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.embed.fields.title.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'provider', 'label' => 'blocks.embed.fields.provider.label', 'type' => 'select', 'default' => 'youtube',
                        'options' => [
                            ['value' => 'youtube', 'label' => 'YouTube'],
                            ['value' => 'vimeo', 'label' => 'Vimeo'],
                            ['value' => 'spotify', 'label' => 'Spotify'],
                            ['value' => 'soundcloud', 'label' => 'SoundCloud'],
                            ['value' => 'iframe', 'label' => 'blocks.embed.fields.provider.options.iframe'],
                        ],
                    ],
                    ['key' => 'url', 'label' => 'blocks.embed.fields.url.label', 'type' => 'url', 'help' => 'blocks.embed.fields.url.help'],
                    ['key' => 'aspect', 'label' => 'blocks.embed.fields.aspect.label', 'type' => 'select', 'default' => '16:9',
                        'options' => [
                            ['value' => '16:9', 'label' => '16:9'],
                            ['value' => '4:3', 'label' => '4:3'],
                            ['value' => '1:1', 'label' => '1:1'],
                            ['value' => '9:16', 'label' => 'blocks.embed.fields.aspect.options.9_16'],
                        ],
                    ],
                ],
            ],

            'contact' => [
                'id' => 'contact',
                'label' => 'blocks.contact.label',
                'icon' => 'lucide:mail',
                'category' => 'blocks.categories.action',
                'description' => 'blocks.contact.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'title', 'label' => 'blocks.contact.fields.title.label', 'type' => 'text', 'default' => 'blocks.contact.fields.title.default'],
                    ['key' => 'subtitle', 'label' => 'blocks.contact.fields.subtitle.label', 'type' => 'text', 'default' => ''],
                    ['key' => 'success_message', 'label' => 'blocks.contact.fields.success_message.label', 'type' => 'text', 'default' => 'blocks.contact.fields.success_message.default'],
                    ['key' => 'fields', 'label' => 'blocks.contact.fields.fields.label', 'type' => 'repeat', 'default' => [
                        ['key' => 'name', 'label' => 'blocks.contact.fields.fields.default.name', 'type' => 'text', 'required' => true],
                        ['key' => 'email', 'label' => 'blocks.contact.fields.fields.default.email', 'type' => 'email', 'required' => true],
                        ['key' => 'message', 'label' => 'blocks.contact.fields.fields.default.message', 'type' => 'textarea', 'required' => true],
                    ],
                        'of' => [
                            ['key' => 'key', 'label' => 'blocks.contact.fields.fields.of.key.label', 'type' => 'text'],
                            ['key' => 'label', 'label' => 'blocks.contact.fields.fields.of.label.label', 'type' => 'text'],
                            ['key' => 'type', 'label' => 'blocks.contact.fields.fields.of.type.label', 'type' => 'select', 'options' => [
                                ['value' => 'text', 'label' => 'blocks.contact.fields.fields.of.type.options.text'],
                                ['value' => 'email', 'label' => 'blocks.contact.fields.fields.of.type.options.email'],
                                ['value' => 'tel', 'label' => 'blocks.contact.fields.fields.of.type.options.tel'],
                                ['value' => 'textarea', 'label' => 'blocks.contact.fields.fields.of.type.options.textarea'],
                            ]],
                            ['key' => 'required', 'label' => 'blocks.contact.fields.fields.of.required.label', 'type' => 'toggle'],
                        ],
                    ],
                ],
            ],

            'group' => [
                'id' => 'group',
                'label' => 'blocks.group.label',
                'icon' => 'lucide:layers',
                'category' => 'blocks.categories.structure',
                'description' => 'blocks.group.description',
                // A group is a layout primitive, not visible chrome. Defaults
                // to half-column so the typical "1 left + 2 stacked right"
                // pattern works out of the box. The user can flip it to
                // 'full' (a full-row stack) via the per-block style override.
                'span' => 'half',
                // No own data fields for now. The group's value lives in
                // its children. Stays an empty array so the registry/admin
                // generic form is happy (it just shows no fields).
                'fields' => [],
            ],

            'divider' => [
                'id' => 'divider',
                'label' => 'blocks.divider.label',
                'icon' => 'lucide:waves',
                'category' => 'blocks.categories.structure',
                'description' => 'blocks.divider.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'style', 'label' => 'blocks.divider.fields.style.label', 'type' => 'select', 'default' => 'tessera',
                        'options' => [
                            ['value' => 'tessera', 'label' => 'blocks.divider.fields.style.options.tessera'],
                            ['value' => 'dots', 'label' => 'blocks.divider.fields.style.options.dots'],
                            ['value' => 'line', 'label' => 'blocks.divider.fields.style.options.line'],
                            ['value' => 'line-double', 'label' => 'blocks.divider.fields.style.options.line-double'],
                            ['value' => 'line-dashed', 'label' => 'blocks.divider.fields.style.options.line-dashed'],
                            ['value' => 'line-dashed-thick', 'label' => 'blocks.divider.fields.style.options.line-dashed-thick'],
                            ['value' => 'diagonal', 'label' => 'blocks.divider.fields.style.options.diagonal'],
                            ['value' => 'wave', 'label' => 'blocks.divider.fields.style.options.wave'],
                            ['value' => 'chevrons', 'label' => 'blocks.divider.fields.style.options.chevrons'],
                            ['value' => 'floral', 'label' => 'blocks.divider.fields.style.options.floral'],
                            ['value' => 'stars', 'label' => 'blocks.divider.fields.style.options.stars'],
                            ['value' => 'space', 'label' => 'blocks.divider.fields.style.options.space'],
                        ],
                    ],
                ],
            ],

            'footer' => [
                'id' => 'footer',
                'label' => 'blocks.footer.label',
                'icon' => 'lucide:flag',
                'category' => 'blocks.categories.structure',
                'description' => 'blocks.footer.description',
                'span' => 'full',
                'fields' => [
                    ['key' => 'text', 'label' => 'blocks.footer.fields.text.label', 'type' => 'text', 'default' => '© ' . date('Y')],
                    ['key' => 'show_powered_by', 'label' => 'blocks.footer.fields.show_powered_by.label', 'type' => 'toggle', 'default' => true, 'help' => 'blocks.footer.fields.show_powered_by.help'],
                    ['key' => 'links', 'label' => 'blocks.footer.fields.links.label', 'type' => 'repeat', 'default' => [],
                        'of' => [
                            ['key' => 'label', 'label' => 'blocks.footer.fields.links.of.label.label', 'type' => 'text'],
                            ['key' => 'url', 'label' => 'blocks.footer.fields.links.of.url.label', 'type' => 'url'],
                        ],
                    ],
                ],
            ],
        ];
    }
}
